output_file: my_output.txt

repeats: 10
sim_length: 10000

pmaterial:
  stiffness: 1000000

force:
  min_force: -1.0
  max_force: 1.0

voxel_size: 0.005

voxels:
  0:
    x: 1
  1:
    x: 2
  2:
    x: 3    
  3:
    x: 4
  4:
    x: 5
  5:
    x: 6   
  6:
    x: 7
  7:
    x: 8
  8:
    x: 9    
  9:
    x: 10
  10:
    x: 11
